@startuml ポテトサラダを作る
title ポテトサラダを作る
:材料を買う;
fork
:ジャガイモをゆでる;
:ジャガイモの皮をむく;
:ジャガイモをつぶす;
end fork
:ニンジンを切る;
:玉ねぎを切る;
:ニンジン玉ねぎをレンジでチンする;
fork
:きゅうりを切る;
:ハムを切る;
end fork
:マヨネーズで和える;
:塩コショウで味を調える;
:完成;

@enduml