@startwbs パフェを作る
title パフェを作るWBS
* パフェを作る
**[#Aqua] 材料を買う
***[#Yellow] スーパーでバナナ、\rアイス、チョコソース、\rコーンフレーク、\r生クリームを買う
**[#Aqua] パフェを作る
***[#Yellow] バナナをスライスする
***[#Yellow] グラスにコーンフレークとアイスをのせる
***[#Yellow] バナナを配置
***[#Yellow] チョコソースをかける
***[#Yellow] 生クリームをかける
@endwbs