@startwbs kare
* カレーライス調理
** 材料の準備
*** 材料を買う合計800円
*** 野菜の下ごしらえ
*** 野菜を切る
*** 鶏肉を切る
*** 塩・胡椒で下味をつける
** 調理
*** 材料を炒める
*** 肉を加えて炒める
*** 煮込む
*** 水を加えて煮込む
*** カレールーを加える
*** 煮る
** 盛り付け
*** ご飯を盛る
*** カレーをかける
@endwbs
